### ISSUE TITLE
Docker-Heroku deployment

### ISSUE THREAD

**Issue by JoniValles** [Arquisoft/dechat_es1a#19]
I was trying to deploy de Docker image on Heroku but since we are using Angular/Node i cant find the way to get running the build image using the Dockerfile. 

This is the one i'm using: 
`FROM node:8.11.2-onbuild
EXPOSE 8443
RUN openssl req \
    -new \
    -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" \
    -keyout privkey.pem \
    -out fullchain.pem
CMD npm run solid start
`

but it only attach the node section. We need to use the Angular section too complete the build like we were running it on local.

**Comment by JoniValles** [comment]
Deployment done at the moment without Docker container, just using Travis.
https://github.com/Arquisoft/dechat_es1a/tree/fix/travis

**Comment by UO204115** [comment]
Great job, can you add how to do it to the readme or an explanation here? I have curiosity on how to do it.

Thanks

**Comment by JoniValles** [comment]
Adding this to to the Travis.yml: 

    deploy:	
            provider: heroku	
            api_key:
                secure: 6af94bee-0789-41b6-9739-c2a35d324b4a
            app: dechates1a
            on:
               all_branches: true

will deploy and build our app on Heroku. 

The API key is the assigned to the account (working on the encrypted one, hope nobody notices it) and for future versions we should change to deploy it only on master branch. 

app is for the App name referenced on the account, we can change it when we want.

**Comment by JoniValles** [comment]
Deployed on Github-Pages
