### ISSUE TITLE
Toy Angular app deploy in Heroku

### ISSUE THREAD

**Issue by UO204115** [Arquisoft/dechat_es1a#24]
To obtain experience in deployment for the moment when it's needed. Will be useful create a Toy app in Angular like a Hello World! and deploy it using Docker and Heroku

**Comment by JoniValles** [comment]
Related issue: https://github.com/Arquisoft/dechat_es1a/issues/19
I just need to finish the Dockerfile to be able to finally deploy the app on Heroku.

**Comment by JoniValles** [comment]
Done on the branch: https://github.com/Arquisoft/dechat_es1a/tree/fix/travis
